// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuV9a0voP7fCPaoWjGCMKv54mbvxcc_mw',
    appId: '1:343642653146:android:fd2ef04f4eee01bdcb00e3',
    messagingSenderId: '343642653146',
    projectId: 'chit-chat-31efd',
    storageBucket: 'chit-chat-31efd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdXI3ustwUdRl2zML_K63UzuAPWQYLwdc',
    appId: '1:343642653146:ios:8fc26d366c476890cb00e3',
    messagingSenderId: '343642653146',
    projectId: 'chit-chat-31efd',
    storageBucket: 'chit-chat-31efd.appspot.com',
    androidClientId: '343642653146-5jaagp3ocd32ajgvin122lmjntumqn41.apps.googleusercontent.com',
    iosClientId: '343642653146-5q4ml5djh9igrh261satcvfb5a65dkf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );
}
